{{/*This describes a K8s service for comunicating with the statefulset*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
    {{- include "bitbucket.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.bitbucket.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.bitbucket.service.type }}
  ports:
    - port: {{ .Values.bitbucket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.bitbucket.ports.ssh }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: {{ .Values.bitbucket.ports.hazelcast }}
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  selector:
    {{- include "bitbucket.selectorLabels" . | nindent 4 }}

{{/* This describes a K8s service for communicating with the ssh port on Bitbucket */}}
{{- if .Values.bitbucket.sshService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitbucket.fullname" . }}-ssh
  labels:
    {{- include "bitbucket.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.bitbucket.sshService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.bitbucket.sshService.type }}
  ports:
    - port: {{ .Values.bitbucket.sshService.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "bitbucket.selectorLabels" . | nindent 4 }}
{{ end }}
